# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-02 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Email'),
        ),
    ]
